server:
  port: 8801
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    primary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.1.107:3306/journal_navication
      username: root
      password: root
    secondary:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://www.dimonho.com:3306/ssoserver
      username: root
      password: root123